droplet_id:
  in: query
  name: host_id
  description: The droplet ID.
  example: "17209102"
  required: true
  schema:
    type: string

app_id:
  in: query
  name: app_id
  description: The app UUID.
  example: "2db3c021-15ad-4088-bfe8-99dc972b9cf6"
  required: true
  schema:
    type: string

load_balancer_id:
  in: query
  name: lb_id
  description: A unique identifier for a load balancer.
  required: true
  schema:
    type: string
  example: 4de7ac8b-495b-4884-9a69-1050c6793cd6

resource_id:
  in: query
  name: resource_id
  description: A unique URN for a resource.
  schema:
    $ref: '../../shared/attributes/urn.yml' 
  example: do:kubernetes:5ba4518b-b9e2-4978-aa92-2d4c727e8824

app_component:
  in: query
  name: app_component
  description: The app component name.
  example: "sample-application"
  required: false
  schema:
    type: string

network_interface:
  in: query
  name: interface
  description: The network interface.
  required: true
  example: "private"
  schema:
    type: string
    enum:
      - private
      - public

network_direction:
  in: query
  name: direction
  description: The traffic direction.
  required: true
  example: "inbound"
  schema:
    type: string
    enum:
      - inbound
      - outbound

autoscale_pool_id:
  in: query
  name: autoscale_pool_id
  description: A unique identifier for an autoscale pool.
  required: true
  schema:
    type: string
  example: 0d3db13e-a604-4944-9827-7ec2642d32ac

metric_timestamp_start:
  in: query
  name: start
  description: UNIX timestamp to start metric window.
  example: "1620683817"
  required: true
  schema:
    type: string

metric_timestamp_end:
  in: query
  name: end
  description: UNIX timestamp to end metric window.
  example: "1620705417"
  required: true
  schema:
    type: string

alert_uuid:
  in: path
  name: alert_uuid
  description: A unique identifier for an alert policy.
  required: true
  schema:
    type: string
  example: 4de7ac8b-495b-4884-9a69-1050c6793cd6

destination_uuid:
  in: path
  name: destination_uuid
  description: A unique identifier for a destination.
  required: true
  schema:
    type: string
  example: 1a64809f-1708-48ee-a742-dec8d481b8d1

sink_uuid:
  in: path
  name: sink_uuid
  description: A unique identifier for a sink.
  required: true
  schema:
    type: string
  example: 78b172b6-52c3-4a4b-96d5-78d3f1a0b18c

# DBaaS MySQL monitoring metrics parameters

db_id:
  in: query
  name: db_id
  required: true
  description: The DBaaS cluster UUID (database ID).
  schema:
    type: string
    format: uuid
  example: 9cc10173-e9ea-4176-9dbc-a4cee4c4ff30

aggregate_avg_max_min:
  in: query
  name: aggregate
  required: true
  description: Aggregation over the time range: avg, max, or min.
  schema:
    type: string
    enum:
      - avg
      - max
      - min
  example: avg

aggregate_avg_max:
  in: query
  name: aggregate
  required: true
  description: Aggregation over the time range: avg or max.
  schema:
    type: string
    enum:
      - avg
      - max
  example: avg

metric_load:
  in: query
  name: metric
  required: true
  description: Load average window: load1, load5, or load15.
  schema:
    type: string
    enum:
      - load1
      - load5
      - load15
  example: load1

metric_op_rates:
  in: query
  name: metric
  required: true
  description: Operation type: select, insert, update, or delete.
  schema:
    type: string
    enum:
      - select
      - insert
      - update
      - delete
  example: select

metric_schema_io:
  in: query
  name: metric
  required: true
  description: Table I/O operation: insert, fetch, update, or delete.
  schema:
    type: string
    enum:
      - insert
      - fetch
      - update
      - delete
  example: insert

schema:
  in: query
  name: schema
  required: true
  description: The schema (database) name.
  schema:
    type: string
  example: defaultdb
